import Providers from "@/components/Providers";
import "../styles/globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/Toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
 
  return (
    <html lang="en" className={inter.className}>
      <body className="min-h-screen bg-slate-50 dark:bg-slate-900 antialiased">
        <Providers>{children}
        <Toaster position="bottom-right"/>
        {/* @ts-expect-error Server Component */}
        <Navbar/>
        </Providers>
        {/* allow for more height on mobile device */}
        <div className="h-40 md:hidden"/>
      </body>
    </html>
  );
}
